#server:
#  port: 3344
#spring:
#  application:
#    name: microservicecloud-config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/GHBigBig/springcloudconfig.git
#          uri: git@github.com:GHBigBig/springcloudconfig.git #GitHub上面的git仓库名字 git 方式报错

spring:
  profiles:
    active:
      - dev

---

spring:
  profiles: dev   #开发环境
  application:
    name: microservicecloud-config-zjg-dev

---

spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-zjg-test

#需保存为 UTF-8 的格式
